[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "elfinguard"
authors = [{name = "Kui Wang", email = "kui.wang@smartbch.org"}]
dynamic = ["version", "description"]

dependencies = [
    "requests>=2.25.0",
]
